export const projectsData = [
  {
    id: 1,
    i18nKey: 'ecommerceApp',
    image: '/projects/ecommerce-app.jpg',
    technologies: ['React Native', 'TypeScript', 'Node.js', 'PostgreSQL', 'Stripe'],
    github: 'https://github.com/ranimontagna/ecommerce-app',
    demo: 'https://ecommerce-demo.ranimontagna.com',
    type: 'mobile',
    featured: true,
  },
  {
    id: 2,
    i18nKey: 'dashboardAnalytics',
    image: '/projects/dashboard-analytics.jpg',
    technologies: ['React', 'Next.js', 'Chart.js', 'Tailwind CSS', 'Firebase'],
    github: 'https://github.com/ranimontagna/dashboard-analytics',
    demo: 'https://dashboard-demo.ranimontagna.com',
    type: 'web',
    featured: true,
  },
  {
    id: 3,
    i18nKey: 'financeApi',
    image: '/projects/finance-api.jpg',
    technologies: ['Node.js', 'Express', 'PostgreSQL', 'JWT', 'Swagger'],
    github: 'https://github.com/ranimontagna/finance-api',
    demo: 'https://finance-api.ranimontagna.com/docs',
    type: 'api',
    featured: false,
  },
  {
    id: 4,
    i18nKey: 'saasLanding',
    image: '/projects/saas-landing.jpg',
    technologies: ['Next.js', 'Framer Motion', 'Tailwind CSS', 'Vercel'],
    github: 'https://github.com/ranimontagna/saas-landing',
    demo: 'https://saas-landing.ranimontagna.com',
    type: 'web',
    featured: false,
  },
  {
    id: 5,
    i18nKey: 'deliveryApp',
    image: '/projects/delivery-app.jpg',
    technologies: ['React Native', 'Firebase', 'Google Maps', 'Redux'],
    github: 'https://github.com/ranimontagna/delivery-app',
    demo: null,
    type: 'mobile',
    featured: true,
  },
  {
    id: 6,
    i18nKey: 'blogCms',
    image: '/projects/blog-cms.jpg',
    technologies: ['Next.js', 'Prisma', 'PostgreSQL', 'NextAuth', 'TinyMCE'],
    github: 'https://github.com/ranimontagna/blog-cms',
    demo: 'https://blog-cms.ranimontagna.com',
    type: 'web',
    featured: false,
  },
]
