const copy = {
  pt: {
    welcome: 'Bem-vindo à homepage do Ranielli!',
    intro: 'Engenheiro de software. Explorador da internet. Desde o futuro.',
    construction: 'EM CONSTRUÇÃO',
    note: 'Como toda boa homepage, esta aqui nunca fica pronta.',
    exit: 'Voltar ao futuro',
    home: 'Início',
    projects: 'Projetos',
    blog: 'Blog',
    contact: 'Contato',
    handmade: 'FEITO À MÃO',
    bestViewed: 'MELHOR EM 800 × 600',
    online: 'VOCÊ ESTÁ ONLINE',
    restored: 'Backup de 1998 restaurado. Bem-vindo à internet de antigamente.',
    returned: 'De volta ao futuro. Visual atual restaurado.',
    web: 'Uma pequena esquina da World Wide Web',
  },
  en: {
    welcome: "Welcome to Ranielli's homepage!",
    intro: 'Software engineer. Internet explorer. Visiting from the future.',
    construction: 'UNDER CONSTRUCTION',
    note: 'Like every good homepage, this one is never finished.',
    exit: 'Back to the future',
    home: 'Home',
    projects: 'Projects',
    blog: 'Blog',
    contact: 'Contact',
    handmade: 'HAND CODED',
    bestViewed: 'BEST VIEWED AT 800 × 600',
    online: 'YOU ARE ONLINE',
    restored: '1998 backup restored. Welcome to the old-school internet.',
    returned: 'Back to the future. Modern appearance restored.',
    web: 'A little corner of the World Wide Web',
  },
  es: {
    welcome: '¡Bienvenido a la homepage de Ranielli!',
    intro: 'Ingeniero de software. Explorador de internet. Desde el futuro.',
    construction: 'EN CONSTRUCCIÓN',
    note: 'Como toda buena homepage, esta nunca está terminada.',
    exit: 'Volver al futuro',
    home: 'Inicio',
    projects: 'Proyectos',
    blog: 'Blog',
    contact: 'Contacto',
    handmade: 'HECHO A MANO',
    bestViewed: 'MEJOR EN 800 × 600',
    online: 'ESTÁS EN LÍNEA',
    restored: 'Backup de 1998 restaurado. Bienvenido al internet de antes.',
    returned: 'De vuelta al futuro. Apariencia actual restaurada.',
    web: 'Un pequeño rincón de la World Wide Web',
  },
}

export function getRetroCopy(locale: string) {
  return copy[locale === 'en' || locale === 'es' ? locale : 'pt']
}
