export const projectsData = [
  {
    id: 1,
    i18nKey: 'northClinic',
    image: null,
    technologies: ['Javascript', 'Golang', 'REST API'],
    github: null,
    demo: 'https://northclinic.com.br',
    type: 'web',
    featured: true,
  },
  {
    id: 2,
    i18nKey: 'mobileEstoquista',
    image: null,
    technologies: ['React Native', 'TypeScript', 'Micro-frontend'],
    github: null,
    demo: null,
    type: 'mobile',
    featured: true,
  },
  {
    id: 3,
    i18nKey: 'pratio',
    image: null,
    technologies: ['React', 'Electron', 'TypeScript'],
    github: null,
    demo: 'https://pratio.com.br',
    type: 'web',
    featured: true,
  },
  {
    id: 4,
    i18nKey: 'smartDs',
    image: null,
    technologies: ['Storybook', 'Material-UI', 'Emotion'],
    github: null,
    demo: null,
    type: 'web',
    featured: false,
  },
  {
    id: 5,
    i18nKey: 'sennaDs',
    image: null,
    technologies: ['Next.js', 'Shadcn', 'Storybook'],
    github: null,
    demo: null,
    type: 'web',
    featured: false,
  },
  {
    id: 6,
    i18nKey: 'alemDoArcoIrisApp',
    image: null,
    technologies: ['Flutter', 'Dart', 'Firebase'],
    github: null,
    demo: null,
    type: 'mobile',
    featured: false,
  },
  {
    id: 7,
    i18nKey: 'motiviumBot',
    image: null,
    technologies: ['Node.js', 'Discord.js', 'REST API'],
    github: 'https://github.com/RanielliMontagna/motivium-bot',
    demo: null,
    type: 'api',
    featured: false,
  },
  {
    id: 8,
    i18nKey: 'tabSwitch',
    image: null,
    technologies: ['React', 'WebExtensions API', 'TypeScript'],
    github: 'https://github.com/RanielliMontagna/tab-switch',
    demo: null,
    type: 'web',
    featured: false,
  },
  {
    id: 9,
    i18nKey: 'pdfGenerator',
    image: '/projects/pdf-generator.jpg',
    technologies: ['Node.js', 'Fastify', 'PDFKit', 'TypeBox'],
    github: 'https://github.com/RanielliMontagna/pdf-generator',
    demo: null,
    type: 'api',
    featured: false,
  },
]
